# Generated by Django 4.1.7 on 2023-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="code",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="Код ISO 3166-2"
            ),
        ),
    ]
