# Generated by Django 4.1.7 on 2023-02-17 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0002_region_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ("name",),
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
            },
        ),
    ]
