# Generated by Django 4.1.7 on 2023-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0003_alter_region_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(
                max_length=7, unique=True, verbose_name="Код ISO 3166-2"
            ),
        ),
    ]
