# Generated by Django 4.1.7 on 2023-02-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=127, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Показатель",
                "verbose_name_plural": "Показатели",
            },
        ),
        migrations.CreateModel(
            name="MeasureUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=31, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
            },
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Значение")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="stats.feature",
                        verbose_name="Показатель",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feature_values",
                        to="geography.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feature",
            name="measure_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="features",
                to="stats.measureunit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
