# Generated by Django 4.1.7 on 2023-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featurevalue",
            options={
                "verbose_name": "Значение показателя",
                "verbose_name_plural": "Значения показателей",
            },
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
    ]
