# Generated by Django 4.1.7 on 2023-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_alter_featurevalue_options_alter_feature_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(max_length=511, verbose_name="Название"),
        ),
    ]
