# Generated by Django 4.1.7 on 2023-02-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0003_alter_feature_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="parent_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_features",
                to="stats.feature",
                verbose_name="Родительский показатель",
            ),
        ),
    ]
