# Generated by Django 4.1.7 on 2023-02-18 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0004_feature_parent_feature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featurevalue",
            options={
                "ordering": ("-value",),
                "verbose_name": "Значение показателя",
                "verbose_name_plural": "Значения показателей",
            },
        ),
    ]
