# Generated by Django 4.1.7 on 2023-02-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0005_alter_featurevalue_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurevalue",
            name="year",
            field=models.PositiveSmallIntegerField(default=2021, verbose_name="Год"),
            preserve_default=False,
        ),
    ]
